 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dak_templates", type: :request do
  # DakTemplate. As you add validations to DakTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DakTemplate.create! valid_attributes
      get dak_templates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dak_template = DakTemplate.create! valid_attributes
      get dak_template_url(dak_template)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dak_template_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dak_template = DakTemplate.create! valid_attributes
      get edit_dak_template_url(dak_template)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DakTemplate" do
        expect {
          post dak_templates_url, params: { dak_template: valid_attributes }
        }.to change(DakTemplate, :count).by(1)
      end

      it "redirects to the created dak_template" do
        post dak_templates_url, params: { dak_template: valid_attributes }
        expect(response).to redirect_to(dak_template_url(DakTemplate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DakTemplate" do
        expect {
          post dak_templates_url, params: { dak_template: invalid_attributes }
        }.to change(DakTemplate, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dak_templates_url, params: { dak_template: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dak_template" do
        dak_template = DakTemplate.create! valid_attributes
        patch dak_template_url(dak_template), params: { dak_template: new_attributes }
        dak_template.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dak_template" do
        dak_template = DakTemplate.create! valid_attributes
        patch dak_template_url(dak_template), params: { dak_template: new_attributes }
        dak_template.reload
        expect(response).to redirect_to(dak_template_url(dak_template))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dak_template = DakTemplate.create! valid_attributes
        patch dak_template_url(dak_template), params: { dak_template: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dak_template" do
      dak_template = DakTemplate.create! valid_attributes
      expect {
        delete dak_template_url(dak_template)
      }.to change(DakTemplate, :count).by(-1)
    end

    it "redirects to the dak_templates list" do
      dak_template = DakTemplate.create! valid_attributes
      delete dak_template_url(dak_template)
      expect(response).to redirect_to(dak_templates_url)
    end
  end
end
