 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/followup_audits", type: :request do
  # FollowupAudit. As you add validations to FollowupAudit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FollowupAudit.create! valid_attributes
      get followup_audits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      followup_audit = FollowupAudit.create! valid_attributes
      get followup_audit_url(followup_audit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_followup_audit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      followup_audit = FollowupAudit.create! valid_attributes
      get edit_followup_audit_url(followup_audit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FollowupAudit" do
        expect {
          post followup_audits_url, params: { followup_audit: valid_attributes }
        }.to change(FollowupAudit, :count).by(1)
      end

      it "redirects to the created followup_audit" do
        post followup_audits_url, params: { followup_audit: valid_attributes }
        expect(response).to redirect_to(followup_audit_url(FollowupAudit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FollowupAudit" do
        expect {
          post followup_audits_url, params: { followup_audit: invalid_attributes }
        }.to change(FollowupAudit, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post followup_audits_url, params: { followup_audit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested followup_audit" do
        followup_audit = FollowupAudit.create! valid_attributes
        patch followup_audit_url(followup_audit), params: { followup_audit: new_attributes }
        followup_audit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the followup_audit" do
        followup_audit = FollowupAudit.create! valid_attributes
        patch followup_audit_url(followup_audit), params: { followup_audit: new_attributes }
        followup_audit.reload
        expect(response).to redirect_to(followup_audit_url(followup_audit))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        followup_audit = FollowupAudit.create! valid_attributes
        patch followup_audit_url(followup_audit), params: { followup_audit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested followup_audit" do
      followup_audit = FollowupAudit.create! valid_attributes
      expect {
        delete followup_audit_url(followup_audit)
      }.to change(FollowupAudit, :count).by(-1)
    end

    it "redirects to the followup_audits list" do
      followup_audit = FollowupAudit.create! valid_attributes
      delete followup_audit_url(followup_audit)
      expect(response).to redirect_to(followup_audits_url)
    end
  end
end
